# Generated by Django 2.1.2 on 2018-10-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('gallery', models.CharField(choices=[('headshots', 'headshots'), ('seniors', 'seniors'), ('events', 'events'), ('maternity', 'maternity'), ('couples', 'couples'), ('engagements', 'engagements'), ('weddings', 'weddings')], max_length=100)),
                ('image_url', models.TextField()),
            ],
        ),
    ]
