# Generated by Django 2.1.2 on 2018-10-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default='', upload_to='review_pic/'),
            preserve_default=False,
        ),
    ]
